version: '3.9'

services:
  nginx:
    container_name: tomoyo-nginx
    image: nginx:1.24.0-alpine
    restart: unless-stopped
    volumes:
      - ./ssl:/etc/ssl:ro
      - ./logs:/var/log/nginx
      - ./templates:/etc/nginx/templates
    environment:
      - NGINX_IMAGE_DOMAIN=image.tana.moe
    ports:
      - "80:80"
      - "443:443"

  imagor:
    container_name: tomoyo-imagor
    image: shumc/imagor:1.4.7
    restart: unless-stopped
    environment:
      - PORT=8000
      - IMAGOR_UNSAFE=1
      - IMAGOR_AUTO_WEBP=1
      - IMAGOR_PROCESS_CONCURRENCY=4
      - IMAGOR_PROCESS_QUEUE_SIZE=50
      - VIPS_MAX_RESOLUTION=16800000
      - VIPS_MAX_WIDTH=5000
      - VIPS_MAX_HEIGHT=5000
      - HTTP_LOADER_BASE_URL=https://pb.tana.moe/api/files

  umami:
    container_name: tomoyo-umami
    build: 
      context: ./build/umami
      args:
        - DATABASE_URL=${UMAMI_DATABASE_URL}
    restart: unless-stopped

