version: '3.9'

services:
  imagor:
    image: shumc/imagor:1.4.7
    restart: unless-stopped
    volumes:
      - ./data:/mnt/data
    environment:
      PORT: 8000

      IMAGOR_UNSAFE: 1
      IMAGOR_AUTO_WEBP: 1
      IMAGOR_PROCESS_CONCURRENCY: 5
      IMAGOR_PROCESS_QUEUE_SIZE: 10

      FILE_LOADER_BASE_DIR: /mnt/data # enable file loader by specifying base dir

      FILE_STORAGE_BASE_DIR: /mnt/data # enable file storage by specifying base dir
      FILE_STORAGE_MKDIR_PERMISSION: 0755 # optional
      FILE_STORAGE_WRITE_PERMISSION: 0666 # optional

      FILE_RESULT_STORAGE_BASE_DIR: /mnt/data/result # enable file result storage by specifying base dir
      FILE_RESULT_STORAGE_MKDIR_PERMISSION: 0755 # optional
      FILE_RESULT_STORAGE_WRITE_PERMISSION: 0666 # optional

      VIPS_MAX_RESOLUTION: 16800000
      VIPS_MAX_WIDTH: 5000
      VIPS_MAX_HEIGHT: 5000
      
      HTTP_LOADER_BASE_URL: https://pb.tana.moe/api/files
    ports:
      - "8000:8000"
