version: '3.9'

services:
  caddy:
    container_name: tomoyo-caddy
    image: caddy:2.7.6-alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  imagor:
    container_name: tomoyo-imagor
    image: shumc/imagor:1.4.8
    restart: unless-stopped
    env_file:
      - imagor.env
    environment:
      - PORT=8000
      - IMAGOR_SIGNER_TYPE=sha256
      - IMAGOR_SIGNER_TRUNCATE=40
      - IMAGOR_AUTO_WEBP=1
      - IMAGOR_PROCESS_CONCURRENCY=2
      - IMAGOR_PROCESS_QUEUE_SIZE=1000
      - VIPS_MAX_RESOLUTION=16800000
      - VIPS_MAX_WIDTH=5000
      - VIPS_MAX_HEIGHT=5000
      - HTTP_LOADER_BASE_URL=https://pb.tana.moe/api/files
      - HTTP_LOADER_FORWARD_CLIENT_HEADERS=1

  umami:
    container_name: tomoyo-umami
    image: umamisoftware/umami:postgresql-v2.9.0
    restart: unless-stopped
    env_file:
      - umami.env
    environment:
      - DATABASE_TYPE=postgresql

volumes:
  caddy_data:
    external: true
  caddy_config:

